# Generated by Django 2.2.8 on 2020-01-20 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20191222_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.IntegerField(default=2019, validators=[django.core.validators.MaxValueValidator(2020), django.core.validators.MinValueValidator(1800)]),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='established',
            field=models.IntegerField(default=2019, validators=[django.core.validators.MaxValueValidator(2020), django.core.validators.MinValueValidator(1800)]),
        ),
    ]
